### ISSUE TITLE
Possibly broken with 13.6

### ISSUE THREAD

**Issue by ElDingo424** [Rerago/LoLWideScreenFix#13] opened 2023-03-23 00:59 UTC
Generates normally, but mod does not seem to work when in game. Attempted ~3 times.

**Comment by javigoncompte** [comment] 2023-03-24 02:20
same here i think new patch broke mod

**Comment by Rerago** [comment] 2023-03-24 15:22
Yes it has unfortunately changed slightly again (should be fixed with v0,7). I really hope that Riot adds such an option natively.

**Closed by Rerago** 2023-03-24 15:22 UTC

**Comment by javigoncompte** [comment] 2023-03-24 15:37
do they change the naming every patch?

**Comment by Rerago** [comment] 2023-03-24 15:54
Partially, the structure is redesigned, such as the patch before:

- a new subobject was introduced which keeps all position settings (good idea)
- they changed from a rectangle to a point (makes it even easier for me)

In this patch they just changed the name from 0xfc2cd44b (no idea what this hash is, `LeagueHashes ` and `CDragon` didn't know it) to "position" which makes sense.

The problem is that these files are not an API. Therefore it happens more often that there are breaking changes. So I really hope that Riot introduces this as an option.

**Comment by Rerago** [comment] 2023-03-24 15:55
Partially, the structure is redesigned, such as the patch before:

- a new subobject was introduced which keeps all position settings (good idea)
- they changed from a rectangle to a point

In this patch they just changed the name from 0xfc2cd44b (no idea what this hash is, `LeagueHashes` and `CDragon` didn't know it) to "position" which makes sense.

The problem is that these files are not an API. Therefore it happens more often that there are breaking changes. So I really hope that Riot introduces this as an option.

**Comment by Rerago** [comment] 2023-03-24 17:55
This time yes, last time they slightly changed the structure.
