### ISSUE TITLE
Hey @Rerago i think its broken again in 13.8

### ISSUE THREAD

**Issue by lilosenpai** [Rerago/LoLWideScreenFix#15] opened 2023-04-24 01:00 UTC
Im having problem to generate the wad file, i dont think im doing something wrong, just trying to recreate the mod after the new patch, but now its giving this error
[9:56:14 PM] Create LoLCustomSkinMod:   FAILED (Decompressed content size cannot be determined (e.g. invalid magic number, srcSize too small))

ps this is the command that im running, LoLWideScreenFix -l "C:\Riot Games\League of Legends" -o "C:\LoLWideScreenFix-0.7-win-x64\output\" -t 1920 -m 2

**Comment by javigoncompte** [comment] 2023-04-25 02:19
i'm getting the same error as well with updated cs lol manager

**Comment by Rerago** [comment] 2023-04-25 13:22
This is not a bug from `LoLWideScreenFix` but from the `LeagueToolkit`. I have opened an issue:

https://github.com/LeagueToolkit/LeagueToolkit/issues/269

**Comment by Rerago** [comment] 2023-04-25 16:38
So I uploaded v0.7.1.

This does not really fix the error (i just ignore it, because the error occurs with files (textures) that we are not interested in). I think in v0.8 the bug will be fixed correctly, but with this version it should work for you again for now.

**Closed by Rerago** 2023-04-25 16:38 UTC
